### ISSUE TITLE
Hardcoded Strava App ID

### ISSUE THREAD

**Issue by ACK-J** [allan-cff/strava-free-year-in-sport#1]
Your Strava client ID is hardcoded into the login OAuth flow.

https://github.com/allan-cff/strava-free-year-in-sport/blob/dd2060c0f08c8c2cb3f2a783b6c920ff12d87ae9/public/login.html#L7-L9

**Comment by allan-cff** [comment]
I added a new api endpoint to index.js to get app id from environnment variable
